# Generated by Django 5.0.4 on 2024-05-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_coursesubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesubscription',
            old_name='user',
            new_name='owner',
        ),
    ]
